# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'windows-2019'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'otel/gradlew'
    options: '--info --no-daemon --stacktrace --warning-mode=all --no-build-cache'
    tasks: 'clean publishToMavenLocal'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    options: '--info -DisBuildServer=true --no-daemon --stacktrace --warning-mode all'
    tasks: 'clean :test:smoke:testApps:CoreAndFilter:smokeTest'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false